"""new fields in user model

Revision ID: 57df1cfaf0a8
Revises: f6cf1b3a49ee
Create Date: 2019-10-28 13:12:17.232174

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '57df1cfaf0a8'
down_revision = 'f6cf1b3a49ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
